name: dark_stories
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Рекомендую расширить диапазон версий SDK

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Пакет для иконок должен быть в dev_dependencies, а не здесь

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Пакет flutter_lints должен быть здесь
  flutter_lints: ^3.0.0 # Используем одну, более новую версию

  # Пакет для генерации иконок. Его правильное место - здесь.
  flutter_launcher_icons: "^0.13.1"


flutter:
  uses-material-design: true

  assets:
    - assets/data/
    # Если ты добавлял шрифты или аудио, они тоже должны быть здесь
    # - assets/audio/
    # - fonts/

  # fonts:
  #   - family: Caveat
  #     fonts:
  #       - asset: fonts/Caveat-VariableFont_wght.ttf


# Эта секция остается без изменений, на верхнем уровне
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "launcher_icon/icon.png"